  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: PROJECT-NAME-NAMESPACE-mysql-pv
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /PROJECT-NAME-NAMESPACE-db
      server: 192.168.0.100
