# 设置源  
FROM BASE_REGISTER_IMAGE

#维护者
MAINTAINER chen-123 <wp8155562@gmail.com>

#ADD wordpress_jenkins_code.tar.gz /opt/chen-123/www/html
COPY src /opt/chen-123/www/html/PROJECT_NAME

#COPY src /var/www/html/PROJECT_NAME

#RUN ["sleep","30"]

#WORKDIR /opt/chen-123/www/html

